"""Ajouter champ email à Participation

Revision ID: 7fbcba7b5604
Revises: abdd32957ae6
Create Date: 2024-10-08 19:21:32.780005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbcba7b5604'
down_revision = 'abdd32957ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.drop_column('instagram')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
