"""Ajout des colonnes prix_min et prix_max

Revision ID: abdd32957ae6
Revises: 
Create Date: 2024-10-07 21:23:32.444935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdd32957ae6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prix_min', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('prix_max', sa.Float(), nullable=False))
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('ventes')
        batch_op.drop_column('prix_minimum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prix_minimum', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('ventes', sa.INTEGER(), nullable=True))
        batch_op.alter_column('nom',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('prix_max')
        batch_op.drop_column('prix_min')

    # ### end Alembic commands ###
